---
title: "Exercise 1_1: Package Installation"
subtitle: 'Advanced Geospatial Data Processing for Social Scientists'
author: Dennis Abel & Stefan Jünger
format: 
  html:
    embed-resources: true
    code-copy: true
editor: visual
callout-icon: false
callout-appearance: minimal
---

### Exercises

This is the first exercise in this workshop, and it is relatively easy and short. Its purpose is to get used to this exercise format and, more importantly, to install all necessary packages for this course.

And here comes our very first exercise (which is not very spatial...):

::: callout-note
## 🏋️ Exercise 1

Please install all packages that are listed at the end of the Introduction slides ("1_Introduction.html"). This is the only exercise where we actively encourage you to directly scroll down to the end of this document and copy+paste the solution.
:::

::: {.callout-caution collapse="true"}
## 💡 Tip

We often recommend using the `easypackages` packages, which can be installed with the command `install.packages("easypackages")`. After loading the package with `library(easypackages)` you can load *and* install packages with the command `easypackages::packages("fancy_package_1", "fancy_package_2", ...)`.

For packages hosted on github, you can use `install.packages(pak)`.

:::

That's it. Please notify us if there are any issues with installing the packages or, more generally, your `R` installation.

...oh, and while you are done and the others are still struggling with package installation:

::: callout-note
## 🏋️ OPTIONAL: Exercise 2

Visit the website <https://thetruesize.com/> and check out how the (projected) sizes of countries can change depending on their location. 

Find out why projections are political - check out the "Equal Earth projection" developed by researchers from ESRI, US National Park Service and Monash University <https://equal-earth.com/equal-earth-projection.html>. This projection is advocated by campaigns such as "Correct the Map" <https://correctthemap.org/> which lobbies for a more equal representation of the Global South.
:::

### Solutions

::: {.callout-tip collapse="true"}
## ✅ Solution 1

```{r}
#| eval: false
library(easypackages)

easypackages::packages(
  "blackmarbler",
  "dplyr",
  "ggplot2",
  "ggrepel",
  "ggspatial",
  "randomForest",
  "readr",
  "scales",
  "sf",
  "stars",
  "terra",
  "tidyterra",
  "tigris",
  "units"
) 
```
:::
